export type Team = {
  id: string;
  team_id: string;
  name: string;
  abbreviation: string;
  conference: string;
  division: string;
  wins: number;
  losses: number;
  home_wins: number;
  home_losses: number;
  away_wins: number;
  away_losses: number;
  ppg: number;
  opp_ppg: number;
  pace: number;
  off_rating: number;
  def_rating: number;
  logo_color: string;
};

export type Player = {
  id: string;
  player_id: string;
  team_id: string;
  name: string;
  position: string;
  age: number;
  height: string;
  weight: number;
  jersey_number: number;
  ppg: number;
  rpg: number;
  apg: number;
  spg: number;
  bpg: number;
  fg_pct: number;
  three_pct: number;
  ft_pct: number;
  per: number;
  true_shooting_pct: number;
  usage_rate: number;
  minutes_per_game: number;
  image_url: string;
  is_active: boolean;
};

export const mockTeams: Team[] = [
  {
    id: '1',
    team_id: 'BOS',
    name: 'Boston Celtics',
    abbreviation: 'BOS',
    conference: 'Eastern',
    division: 'Atlantic',
    wins: 57,
    losses: 25,
    home_wins: 31,
    home_losses: 10,
    away_wins: 26,
    away_losses: 15,
    ppg: 117.9,
    opp_ppg: 109.2,
    pace: 98.3,
    off_rating: 117.5,
    def_rating: 108.9,
    logo_color: '#007A33'
  },
  {
    id: '2',
    team_id: 'LAL',
    name: 'Los Angeles Lakers',
    abbreviation: 'LAL',
    conference: 'Western',
    division: 'Pacific',
    wins: 47,
    losses: 35,
    home_wins: 27,
    home_losses: 14,
    away_wins: 20,
    away_losses: 21,
    ppg: 114.3,
    opp_ppg: 112.8,
    pace: 97.8,
    off_rating: 114.1,
    def_rating: 112.6,
    logo_color: '#552583'
  },
  {
    id: '3',
    team_id: 'GSW',
    name: 'Golden State Warriors',
    abbreviation: 'GSW',
    conference: 'Western',
    division: 'Pacific',
    wins: 46,
    losses: 36,
    home_wins: 25,
    home_losses: 16,
    away_wins: 21,
    away_losses: 20,
    ppg: 115.7,
    opp_ppg: 111.2,
    pace: 99.1,
    off_rating: 115.9,
    def_rating: 111.4,
    logo_color: '#1D428A'
  },
  {
    id: '4',
    team_id: 'MIA',
    name: 'Miami Heat',
    abbreviation: 'MIA',
    conference: 'Eastern',
    division: 'Southeast',
    wins: 44,
    losses: 38,
    home_wins: 24,
    home_losses: 17,
    away_wins: 20,
    away_losses: 21,
    ppg: 109.8,
    opp_ppg: 107.6,
    pace: 96.7,
    off_rating: 109.9,
    def_rating: 107.7,
    logo_color: '#98002E'
  },
  {
    id: '5',
    team_id: 'DEN',
    name: 'Denver Nuggets',
    abbreviation: 'DEN',
    conference: 'Western',
    division: 'Northwest',
    wins: 54,
    losses: 28,
    home_wins: 29,
    home_losses: 12,
    away_wins: 25,
    away_losses: 16,
    ppg: 115.4,
    opp_ppg: 108.9,
    pace: 97.2,
    off_rating: 115.7,
    def_rating: 109.2,
    logo_color: '#0E2240'
  }
];

export const mockPlayers: Player[] = [
  // Boston Celtics
  {
    id: '1',
    player_id: 'jayson_tatum',
    team_id: 'BOS',
    name: 'Jayson Tatum',
    position: 'SF',
    age: 26,
    height: '6-8',
    weight: 235,
    jersey_number: 0,
    ppg: 27.1,
    rpg: 8.3,
    apg: 4.9,
    spg: 1.1,
    bpg: 0.7,
    fg_pct: 0.473,
    three_pct: 0.376,
    ft_pct: 0.832,
    per: 23.8,
    true_shooting_pct: 0.581,
    usage_rate: 28.7,
    minutes_per_game: 35.9,
    image_url: '',
    is_active: true
  },
  {
    id: '2',
    player_id: 'jaylen_brown',
    team_id: 'BOS',
    name: 'Jaylen Brown',
    position: 'SG',
    age: 27,
    height: '6-6',
    weight: 223,
    jersey_number: 7,
    ppg: 23.1,
    rpg: 5.5,
    apg: 3.6,
    spg: 1.2,
    bpg: 0.5,
    fg_pct: 0.492,
    three_pct: 0.349,
    ft_pct: 0.708,
    per: 19.2,
    true_shooting_pct: 0.563,
    usage_rate: 25.3,
    minutes_per_game: 33.5,
    image_url: '',
    is_active: true
  },
  {
    id: '3',
    player_id: 'jrue_holiday',
    team_id: 'BOS',
    name: 'Jrue Holiday',
    position: 'PG',
    age: 34,
    height: '6-4',
    weight: 205,
    jersey_number: 4,
    ppg: 12.5,
    rpg: 5.4,
    apg: 4.8,
    spg: 1.2,
    bpg: 0.8,
    fg_pct: 0.485,
    three_pct: 0.429,
    ft_pct: 0.821,
    per: 16.7,
    true_shooting_pct: 0.589,
    usage_rate: 16.2,
    minutes_per_game: 28.0,
    image_url: '',
    is_active: true
  },
  // Los Angeles Lakers
  {
    id: '4',
    player_id: 'lebron_james',
    team_id: 'LAL',
    name: 'LeBron James',
    position: 'SF',
    age: 39,
    height: '6-9',
    weight: 250,
    jersey_number: 23,
    ppg: 25.7,
    rpg: 7.3,
    apg: 8.3,
    spg: 1.3,
    bpg: 0.5,
    fg_pct: 0.540,
    three_pct: 0.410,
    ft_pct: 0.750,
    per: 25.4,
    true_shooting_pct: 0.632,
    usage_rate: 29.9,
    minutes_per_game: 35.5,
    image_url: '',
    is_active: true
  },
  {
    id: '5',
    player_id: 'anthony_davis',
    team_id: 'LAL',
    name: 'Anthony Davis',
    position: 'PF',
    age: 31,
    height: '6-10',
    weight: 253,
    jersey_number: 3,
    ppg: 24.7,
    rpg: 12.6,
    apg: 3.5,
    spg: 1.2,
    bpg: 2.3,
    fg_pct: 0.556,
    three_pct: 0.271,
    ft_pct: 0.814,
    per: 26.1,
    true_shooting_pct: 0.604,
    usage_rate: 27.8,
    minutes_per_game: 35.4,
    image_url: '',
    is_active: true
  },
  {
    id: '6',
    player_id: 'dangelo_russell',
    team_id: 'LAL',
    name: "D'Angelo Russell",
    position: 'PG',
    age: 28,
    height: '6-4',
    weight: 193,
    jersey_number: 1,
    ppg: 18.0,
    rpg: 3.1,
    apg: 6.3,
    spg: 0.9,
    bpg: 0.5,
    fg_pct: 0.456,
    three_pct: 0.415,
    ft_pct: 0.828,
    per: 17.9,
    true_shooting_pct: 0.567,
    usage_rate: 22.1,
    minutes_per_game: 30.3,
    image_url: '',
    is_active: true
  },
  // Golden State Warriors
  {
    id: '7',
    player_id: 'stephen_curry',
    team_id: 'GSW',
    name: 'Stephen Curry',
    position: 'PG',
    age: 36,
    height: '6-2',
    weight: 185,
    jersey_number: 30,
    ppg: 26.4,
    rpg: 4.5,
    apg: 5.1,
    spg: 0.7,
    bpg: 0.4,
    fg_pct: 0.452,
    three_pct: 0.408,
    ft_pct: 0.921,
    per: 24.7,
    true_shooting_pct: 0.627,
    usage_rate: 28.4,
    minutes_per_game: 32.7,
    image_url: '',
    is_active: true
  },
  {
    id: '8',
    player_id: 'klay_thompson',
    team_id: 'GSW',
    name: 'Klay Thompson',
    position: 'SG',
    age: 34,
    height: '6-6',
    weight: 220,
    jersey_number: 11,
    ppg: 17.9,
    rpg: 3.3,
    apg: 2.3,
    spg: 0.6,
    bpg: 0.4,
    fg_pct: 0.432,
    three_pct: 0.387,
    ft_pct: 0.869,
    per: 15.8,
    true_shooting_pct: 0.562,
    usage_rate: 20.3,
    minutes_per_game: 29.3,
    image_url: '',
    is_active: true
  },
  {
    id: '9',
    player_id: 'draymond_green',
    team_id: 'GSW',
    name: 'Draymond Green',
    position: 'PF',
    age: 34,
    height: '6-6',
    weight: 230,
    jersey_number: 23,
    ppg: 8.0,
    rpg: 7.2,
    apg: 6.0,
    spg: 1.0,
    bpg: 0.9,
    fg_pct: 0.497,
    three_pct: 0.395,
    ft_pct: 0.731,
    per: 14.3,
    true_shooting_pct: 0.558,
    usage_rate: 14.8,
    minutes_per_game: 27.1,
    image_url: '',
    is_active: true
  },
  // Miami Heat
  {
    id: '10',
    player_id: 'jimmy_butler',
    team_id: 'MIA',
    name: 'Jimmy Butler',
    position: 'SF',
    age: 35,
    height: '6-7',
    weight: 230,
    jersey_number: 22,
    ppg: 20.8,
    rpg: 5.4,
    apg: 5.0,
    spg: 1.3,
    bpg: 0.7,
    fg_pct: 0.497,
    three_pct: 0.341,
    ft_pct: 0.865,
    per: 18.9,
    true_shooting_pct: 0.583,
    usage_rate: 24.5,
    minutes_per_game: 33.4,
    image_url: '',
    is_active: true
  },
  {
    id: '11',
    player_id: 'bam_adebayo',
    team_id: 'MIA',
    name: 'Bam Adebayo',
    position: 'C',
    age: 27,
    height: '6-9',
    weight: 255,
    jersey_number: 13,
    ppg: 19.3,
    rpg: 10.4,
    apg: 3.9,
    spg: 1.1,
    bpg: 0.9,
    fg_pct: 0.523,
    three_pct: 0.088,
    ft_pct: 0.806,
    per: 18.7,
    true_shooting_pct: 0.558,
    usage_rate: 22.7,
    minutes_per_game: 33.6,
    image_url: '',
    is_active: true
  },
  {
    id: '12',
    player_id: 'tyler_herro',
    team_id: 'MIA',
    name: 'Tyler Herro',
    position: 'SG',
    age: 24,
    height: '6-5',
    weight: 195,
    jersey_number: 14,
    ppg: 20.8,
    rpg: 5.3,
    apg: 4.5,
    spg: 0.6,
    bpg: 0.3,
    fg_pct: 0.447,
    three_pct: 0.396,
    ft_pct: 0.864,
    per: 16.8,
    true_shooting_pct: 0.564,
    usage_rate: 23.9,
    minutes_per_game: 33.0,
    image_url: '',
    is_active: true
  },
  // Denver Nuggets
  {
    id: '13',
    player_id: 'nikola_jokic',
    team_id: 'DEN',
    name: 'Nikola Jokić',
    position: 'C',
    age: 29,
    height: '6-11',
    weight: 284,
    jersey_number: 15,
    ppg: 29.7,
    rpg: 13.7,
    apg: 8.7,
    spg: 1.3,
    bpg: 0.9,
    fg_pct: 0.583,
    three_pct: 0.359,
    ft_pct: 0.817,
    per: 31.3,
    true_shooting_pct: 0.653,
    usage_rate: 28.9,
    minutes_per_game: 34.6,
    image_url: '',
    is_active: true
  },
  {
    id: '14',
    player_id: 'jamaal_murray',
    team_id: 'DEN',
    name: 'Jamal Murray',
    position: 'PG',
    age: 27,
    height: '6-4',
    weight: 215,
    jersey_number: 27,
    ppg: 21.2,
    rpg: 4.1,
    apg: 6.5,
    spg: 1.0,
    bpg: 0.3,
    fg_pct: 0.481,
    three_pct: 0.425,
    ft_pct: 0.854,
    per: 19.8,
    true_shooting_pct: 0.586,
    usage_rate: 24.2,
    minutes_per_game: 31.4,
    image_url: '',
    is_active: true
  },
  {
    id: '15',
    player_id: 'aaron_gordon',
    team_id: 'DEN',
    name: 'Aaron Gordon',
    position: 'PF',
    age: 29,
    height: '6-8',
    weight: 235,
    jersey_number: 32,
    ppg: 13.9,
    rpg: 6.5,
    apg: 3.5,
    spg: 0.8,
    bpg: 0.6,
    fg_pct: 0.556,
    three_pct: 0.291,
    ft_pct: 0.614,
    per: 15.2,
    true_shooting_pct: 0.578,
    usage_rate: 16.8,
    minutes_per_game: 29.7,
    image_url: '',
    is_active: true
  }
];
